language: go
sudo: false

go:
  - "1.15.x"

install:
  - go version
  - export GOBIN="$GOPATH/bin"
  - export PATH="$PATH:$GOBIN"
  - go get -u golang.org/x/lint
  - go get golang.org/x/tools/cmd/goimports

script:
  - go test ./...
  - go build
  - diff <(goimports -d *.go) <(printf "")

after_success:
  - diff <(golint ./...) <(printf "")
