language: go
sudo: false

go:
  - "1.15.x"

install:
  - go version
  - export GOBIN="$GOPATH/bin"
  - export PATH="$PATH:$GOBIN"
  - go get -u github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/goimports

script:
  - go test ./...
  - go build -mod=vendor
  - diff <(goimports -d *.go) <(printf "")

after_success:
  - diff <(golint ./...) <(printf "")
